#!/bin/bash

set -eu -o pipefail

# Update the system
sudo apt -y update

# Install new packages
sudo apt install -y python3-pip git micro build-essential

# Remove kernel packages
sudo apt -y --purge remove linux-image-generic-hwe-20.04 "^linux-.*5\..*"

# Absolutely remove all kernels
sudo rm -f /boot/*5*

# Add base kernel after removing HWE kernel
sudo apt -y install linux-generic

# Remove extra packages
sudo apt -y --purge remove \
"^alsa.*" \
"^avahi.*" \
acl \
acpid \
alsa-utils \
apparmor \
apport \
appstream \
apt-utils \
aspell \
"^busybox.*" \
bc \
bluez \
brltty \
"^cups.*" \
ed \
eject \
enchant-2 \
eog \
evince \
file \
"^fonts-lohit-.*" \
"^fonts-noto.*" \
"^fonts-samyak.*" \
"^fonts-smc.*" \
"^fonts-tlwg-.*" \
fonts-freefont-ttf \
fonts-guru \
fonts-guru-extra \
fonts-kacst \
fonts-kacst-one \
fonts-khmeros-core \
fonts-lao \
fonts-liberation2 \
fonts-lklug-sinhala \
fonts-lohit-guru \
fonts-nakula \
fonts-nanum \
fonts-navilu \
fonts-noto-cjk \
fonts-opensymbol \
fonts-orya \
fonts-pagul \
fonts-sarai \
fonts-sil-abyssinica \
fonts-sil-padauk \
fonts-takao-pgothic \
fonts-taml \
fonts-telu \
fonts-tibetan-machine \
fonts-urw-base35 \
foomatic-db-compressed-ppds \
fprintd \
fuse \
gamemode \
gdb \
gedit \
genisoimage \
ghostscript \
gnome-accessibility-themes \
gnome-bluetooth \
gnome-calculator \
gnome-characters \
gnome-disk-utility \
gnome-font-viewer \
gnome-getting-started-docs \
gnome-initial-setup \
gnome-keyring-pkcs11 \
gnome-logs \
gnome-menus \
gnome-online-accounts \
gnome-power-manager \
gnome-session-canberra \
gnome-shell-extesion-appindicator \
gnome-startup-applications \
gnome-system-monitor \
gnome-themes-extra \
gnome-themes-extra-data \
gpg \
gpg-agent \
gstreamer1.0-alsa \
gstreamer1.0-gl \
gstreamer1.0-pulseaudio \
gstreamer1.0-tools \
gstreamer1.0-plugins-good \
hdparm \
humanity-icon-theme \
"^ibus.*" \
info \
iptables \
kerneloops \
language-selector-common \
language-selector-gnome \
libllvm9 \
libgnome-menu-3-0 \
linux-sound-base \
locales \
logrotate \
lshw \
ltrace \
memtest86+ \
mobile-broadband-provider-info \
modemmanager \
mousetweaks \
mtr-tiny \
nautilus-sendto \
network-manager-config-connectivity-ubuntu \
network-manager-gnome \
ntfs-3g \
openprinting-ppds \
openvpn \
os-prober \
"^printer-driver.*" \
packagekit \
pciutils \
pcmciautils \
plymouth \
poppler-data \
poppler-utils \
popularity-contest \
powermgmt-base \
ppp \
psmisc \
publicsuffix \
pulseaudio \
python3-cairo \
rfkill \
rsync \
rsyslog \
rygel \
snapd \
speech-dispatcher \
squashfs-tools \
strace \
switcheroo-control \
system-config-printer-udev \
tcpdump \
ubuntu-advantage-tools \
ubuntu-docs \
ubuntu-report \
ufw \
unattended-upgrades \
update-inetd \
update-manager \
update-manager-core \
update-notifier \
usb-modeswitch \
usbmuxd \
usbutils \
wamerican \
wbritish \
whiptail \
whoopsie \
xcursor-themes \
xdg-user-dirs \
xdg-utils \
xfonts-encodings \
xserver-xephyr \
xserver-xorg-input-wacom \
xserver-xorg-legacy \
xserver-xorg-video-all \
xul-ext-ubufox \
yaru-theme-icon \
yaru-theme-sound \
yelp

# For a very minimal install, uncomment the following
# This will include only gnome-terminal
# sudo apt -y --purge remove gnome-screenshot file-roller nautilus firefox

# Remove dependencies
sudo apt -y --purge autoremove

# Upgrade the system
sudo apt -y upgrade

# Remove temp files
sudo apt clean
shopt -s dotglob
rm -rf /home/user/*
sudo rm -rf /root/*
sudo rm -rf /tmp/*
sudo rm -rf /var/log/*
sudo rm -rf /var/backups/*
sudo rm -rf /var/cache/*
sudo rm -rf /var/lib/apt/lists

# Remove backgrounds
sudo rm -rf /usr/share/backgrounds/*

# Remove old boot images
sudo rm -f /boot/*.old

# Zero free space
dd bs=4M if=/dev/zero of=/var/tmp/empty || rm /var/tmp/empty

# Adjust Gnome settings
# Disable screen blanking
gsettings set org.gnome.desktop.session idle-delay 0
# Disable screen locking after suspend
gsettings set org.gnome.desktop.lockdown disable-lock-screen true
# Disable screen locking from screensaver
gsettings set org.gnome.desktop.screensaver lock-enabled false
# Use black background color
gsettings set org.gnome.desktop.background primary-color '#000000'

# Shut down
sudo shutdown now
