#!/bin/bash

# Update the system
sudo apt -y update

# Install new packages
sudo apt install -y python3-pip git micro build-essential

# Remove extra packages
sudo apt -y --purge remove alsa alsa-utils pulseaudio snapd whoopsie apport apparmor update-manager update-notifier unattended-upgrades bluez enchant-2 wamerican wbritish speech-dispatcher brltty gnome-accessibility-themes gnome-bluetooth gnome-calculator gnome-characters gnome-disk-utility gnome-font-viewer gnome-getting-started-docs gnome-initial-setup gnome-logs gnome-online-accounts gnome-themes-extra gnome-themes-extra-data ubuntu-advantage-tools ubuntu-docs ubuntu-report yaru-theme-sound yaru-theme-icon yelp apt-utils "^fonts-noto.*" linux-image-generic-hwe-20.04 "^linux-.*5\..*"

# Add base kernel after removing HWE kernel
sudo apt -y install linux-generic

# Remove dependencies
sudo apt -y --purge autoremove

# Upgrade the system
sudo apt -y upgrade

# Remove temp files
sudo apt clean
rm -rf /home/user/*
rm -rf /home/user/.*
sudo rm -rf /tmp/*
sudo rm -rf /var/log/*
sudo rm -rf /var/cache/*
sudo rm -rf /var/lib/apt/lists

# Remove old boot images
sudo rm /boot/*.old

# Zero free space    
dd bs=4M if=/dev/zero of=/var/tmp/empty; rm /var/tmp/empty

# Shut down
sudo shutdown now
