#!/bin/bash

set -eu -o pipefail

# Update the system
sudo apt -y update

# Install new packages (xclip is used by micro)
sudo apt install -y python3-pip git build-essential xclip upx-ucl initramfs-tools

# Install micro from Github
sudo wget https://github.com/zyedidia/micro/releases/download/v2.0.8/micro-2.0.8-linux64-static.tar.gz
sudo tar -xvf micro-*.tar.gz
sudo rm micro-*.tar.gz
sudo mv micro-*/micro /usr/bin

# Compress larger bins
sudo upx -9 /usr/bin/micro

# Remove kernel packages
sudo apt -y --purge remove linux-image-generic-hwe-20.04 "^linux-.*5\..*"

# Absolutely remove all kernels
sudo rm -f /boot/*5*

# Add base kernel after removing HWE kernel
sudo apt -y install linux-generic

# Build a slim initramfs
sudo sed -i 's/^MODULES=most/MODULES=dep/' /etc/initramfs-tools/initramfs.conf
sudo mkinitramfs -c xz -o /boot/initrd.img-*

# Remove kernel name map
sudo rm -f /boot/System.map*

# Remove extra packages
sudo apt -y --purge remove \
"^alsa.*" \
anacron \
"^avahi.*" \
acl \
acpid \
alsa-utils \
apparmor \
apport \
appstream \
app-install-data-partner \
apt-utils \
aspell \
"^busybox.*" \
bc \
bluez \
brltty \
build-essential \
cron \
"^cups.*" \
ed \
eject \
enchant-2 \
eog \
evince \
file \
"^fonts-lohit-.*" \
"^fonts-noto.*" \
"^fonts-samyak.*" \
"^fonts-smc.*" \
"^fonts-tlwg-.*" \
fonts-freefont-ttf \
fonts-guru \
fonts-guru-extra \
fonts-kacst \
fonts-kacst-one \
fonts-khmeros-core \
fonts-lao \
fonts-liberation2 \
fonts-lklug-sinhala \
fonts-lohit-guru \
fonts-nakula \
fonts-nanum \
fonts-navilu \
fonts-noto-cjk \
fonts-opensymbol \
fonts-orya \
fonts-pagul \
fonts-sarai \
fonts-sil-abyssinica \
fonts-sil-padauk \
fonts-takao-pgothic \
fonts-taml \
fonts-telu \
fonts-tibetan-machine \
fonts-urw-base35 \
foomatic-db-compressed-ppds \
fprintd \
fuse \
gamemode \
gdb \
gedit \
genisoimage \
ghostscript \
gnome-accessibility-themes \
gnome-bluetooth \
gnome-calculator \
gnome-characters \
gnome-disk-utility \
gnome-font-viewer \
gnome-getting-started-docs \
gnome-initial-setup \
gnome-keyring-pkcs11 \
gnome-logs \
gnome-menus \
gnome-online-accounts \
gnome-power-manager \
gnome-session-canberra \
gnome-shell-extension-appindicator \
gnome-startup-applications \
gnome-system-monitor \
gnome-themes-extra \
gnome-themes-extra-data \
gpg \
gpg-agent \
gstreamer1.0-alsa \
gstreamer1.0-gl \
gstreamer1.0-pulseaudio \
gstreamer1.0-tools \
gstreamer1.0-plugins-good \
hdparm \
humanity-icon-theme \
"^ibus.*" \
info \
initramfs-tools \
iptables \
irqbalance \
kerneloops \
language-selector-common \
language-selector-gnome \
libllvm9 \
libgnome-menu-3-0 \
libproxy1-plugin-networkmanager \
linux-sound-base \
locales \
logrotate \
lshw \
ltrace \
memtest86+ \
micro \
mobile-broadband-provider-info \
modemmanager \
mousetweaks \
mtr-tiny \
nautilus-sendto \
netbase \
netplan.io \
networkd-dispatcher \
network-manager-config-connectivity-ubuntu \
network-manager-gnome \
network-manager \
ntfs-3g \
openprinting-ppds \
openvpn \
os-prober \
"^printer-driver.*" \
packagekit \
pciutils \
pcmciautils \
plymouth \
poppler-data \
poppler-utils \
popularity-contest \
powermgmt-base \
ppp \
psmisc \
publicsuffix \
pulseaudio \
python3-cairo \
rfkill \
rsync \
rsyslog \
rygel \
snapd \
speech-dispatcher \
squashfs-tools \
strace \
switcheroo-control \
system-config-printer-udev \
tcpdump \
ubuntu-advantage-tools \
ubuntu-docs \
ubuntu-report \
ufw \
unattended-upgrades \
update-inetd \
update-manager \
update-manager-core \
update-notifier \
upx-ucl \
usb-modeswitch \
usbmuxd \
usbutils \
vim-tiny \
wamerican \
wbritish \
whiptail \
wireless-tools \
whoopsie \
wpasupplicant \
xcursor-themes \
xdg-user-dirs \
xdg-utils \
xfonts-encodings \
xorg-docs-core \
xserver-xephyr \
xserver-xorg-input-wacom \
xserver-xorg-legacy \
xserver-xorg-video-all \
xul-ext-ubufox \
yaru-theme-icon \
yaru-theme-sound \
yelp

# For a very minimal install, uncomment the following
# This will include only gnome-terminal
# sudo apt -y --purge remove gnome-screenshot file-roller nautilus firefox

# Add basic networking
sudo apt -y install ifupdown
# Show boot messages instead of splash screen
echo 'GRUB_CMDLINE_LINUX_DEFAULT=""' | sudo tee -a /etc/default/grub
# Use old standard names for interfaces (e.g eth0)
echo 'GRUB_CMDLINE_LINUX=" net.ifnames=0 biosdevname=0"' | sudo tee -a /etc/default/grub
sudo update-grub
echo allow-hotplug eth0 | sudo tee /etc/network/interfaces
echo iface eth0 inet dhcp | sudo tee -a /etc/network/interfaces

# Add just make and gcc
sudo apt -y install make gcc

# Remove dependencies
sudo apt -y --purge autoremove

# Upgrade the system
sudo apt -y upgrade

# Remove swapfile
sudo swapoff -a
sudo rm -f /swapfile
sudo sed -i 's/^\/swapfile/\#\/swapfile/' /etc/fstab

# Remove temp files
sudo apt clean
rm -rf /home/user/{.[!.],}*
sudo rm -rf /root/{.[!.],}*
sudo rm -rf /tmp/{.[!.],}*
sudo rm -rf /var/log/*
sudo rm -rf /var/backups/*
sudo rm -rf /var/cache/*
sudo rm -rf /var/lib/apt/lists
sudo rm -rf /var/lib/dpkg/*-old

# Remove backgrounds
sudo rm -rf /usr/share/backgrounds/*

# Remove old boot images
sudo rm -f /boot/*.old

# Remove extra kernel modules
sudo rm -rf /lib/modules/*/build
sudo rm -rf /lib/modules/*/kernel/sound
sudo rm -rf /lib/modules/*/kernel/zfs
sudo rm -rf /lib/modules/*/kernel/wireguard
sudo rm -rf /lib/modules/*/kernel/net/wireless
sudo rm -rf /lib/modules/*/kernel/net/bluetooth
sudo rm -rf /lib/modules/*/kernel/fs/ocfs2
sudo rm -rf /lib/modules/*/kernel/fs/btrfs
sudo rm -rf /lib/modules/*/kernel/fs/xfs
sudo rm -rf /lib/modules/*/kernel/fs/nfs
sudo rm -rf /lib/modules/*/kernel/fs/nls
sudo rm -rf /lib/modules/*/kernel/drivers/wireless
sudo rm -rf /lib/modules/*/kernel/drivers/bluetooth
sudo rm -rf /lib/modules/*/kernel/drivers/hwmon
sudo rm -rf /lib/modules/*/kernel/drivers/staging
sudo rm -rf /lib/modules/*/kernel/drivers/infiniband
sudo rm -rf /lib/modules/*/kernel/drivers/media
sudo rm -rf /lib/modules/*/kernel/drivers/scsi
sudo rm -rf /lib/modules/*/kernel/drivers/iio
sudo rm -rf /lib/modules/*/kernel/drivers/net/wireless
sudo rm -rf /lib/modules/*/kernel/drivers/net/usb
sudo rm -rf /lib/modules/*/kernel/drivers/net/can
sudo rm -rf /lib/modules/*/kernel/drivers/usb/misc
sudo rm -rf /lib/modules/*/kernel/drivers/usb/serial
sudo rm -rf /lib/modules/*/kernel/drivers/usb/gadget
sudo find /lib/modules/*/kernel/drivers/net/ethernet/ -mindepth 1 -maxdepth 1 -not -name intel -not -name amd -not -name realtek -exec rm -rf {} \;
sudo find /lib/modules/*/kernel/drivers/gpu/drm/ -mindepth 1 -maxdepth 1  -type d -not -name virtio -not -name vboxvideo -not -name cirrus -not -name vmwgfx -not -name qxl -not -name ttm -exec rm -rf {} \;

# Remove graphics drivers
# (Intel, Radeon, Nouveau)
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/i* 
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/r* 
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/n*
sudo rm -f /usr/lib/x86_64-linux-gnu/dri/zlink_dri.so

# Remove firmware files unused by VM
sudo rm -rf /usr/lib/firmware

# Adjust Gnome settings
# Disable screen blanking
gsettings set org.gnome.desktop.session idle-delay 0
# Disable screen locking after suspend
gsettings set org.gnome.desktop.lockdown disable-lock-screen true
# Disable screen locking from screensaver
gsettings set org.gnome.desktop.screensaver lock-enabled false
# Use gradient background color
gsettings set org.gnome.desktop.background primary-color '#992233'
gsettings set org.gnome.desktop.background secondary-color '#550055'
gsettings set org.gnome.desktop.background color-shading-type vertical
gsettings set org.gnome.desktop.background picture-options 'none'
gsettings set org.gnome.desktop.background picture-uri ''
# Disable animations
gsettings set org.gnome.desktop.interface enable-animations false

# Add terminal to favorites
dconf write /org/gnome/shell/favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"

# Recreate important paths that may have been deleted
mkdir /home/user/Desktop

# Set default editor
echo export EDITOR=micro > /home/user/.bashrc

# Improve boot time by disabling slower services
sudo systemctl disable udisks2
sudo systemctl disable systemd-timesyncd.service

echo Waiting 3 seconds before scrubbing free space...
sleep 3

# Zero free space
sudo dd bs=4M if=/dev/zero of=/var/tmp/empty || sudo rm -f /var/tmp/empty

echo "Powering off in 3 seconds..."
sleep 3

# Shut down
sudo shutdown now
