#!/bin/bash

set -eu -o pipefail

# Update the system
sudo apt -y update

# Install new packages (xclip is used by micro)
sudo apt install -y python3-pip git xclip upx-ucl initramfs-tools virtualbox-guest-utils lxrandr

# Install micro from Github
sudo wget https://github.com/zyedidia/micro/releases/download/v2.0.8/micro-2.0.8-linux64-static.tar.gz
sudo tar -xvf micro-*.tar.gz
sudo rm micro-*.tar.gz
sudo mv micro-*/micro /usr/bin

# Compress larger bins
sudo upx -9 /usr/bin/micro

# Remove extra packages
sudo apt -y --purge remove \
"^alsa.*" \
anacron \
"^avahi.*" \
acl \
acpid \
alsa-utils \
apparmor \
apport \
appstream \
app-install-data-partner \
apt-utils \
aspell \
"^busybox.*" \
bc \
bluez \
bolt \
brltty \
build-essential \
console-setup \
cron \
"^cups.*" \
dosfstools \
ed \
eject \
enchant-2 \
eog \
evince \
file \
"^fonts-lohit-.*" \
"^fonts-noto.*" \
"^fonts-samyak.*" \
"^fonts-smc.*" \
"^fonts-tlwg-.*" \
fonts-freefont-ttf \
fonts-guru \
fonts-guru-extra \
fonts-kacst \
fonts-kacst-one \
fonts-khmeros-core \
fonts-lao \
fonts-liberation2 \
fonts-lklug-sinhala \
fonts-lohit-guru \
fonts-nakula \
fonts-nanum \
fonts-navilu \
fonts-noto-cjk \
fonts-opensymbol \
fonts-orya \
fonts-pagul \
fonts-sarai \
fonts-sil-abyssinica \
fonts-sil-padauk \
fonts-takao-pgothic \
fonts-taml \
fonts-telu \
fonts-tibetan-machine \
fonts-urw-base35 \
foomatic-db-compressed-ppds \
fprintd \
fuse \
gamemode \
gdb \
gedit \
genisoimage \
ghostscript \
gnome-accessibility-themes \
gnome-bluetooth \
gnome-calculator \
gnome-characters \
gnome-disk-utility \
gnome-font-viewer \
gnome-getting-started-docs \
gnome-initial-setup \
gnome-keyring-pkcs11 \
gnome-logs \
gnome-menus \
gnome-online-accounts \
gnome-power-manager \
gnome-session-canberra \
gnome-shell-extension-appindicator \
gnome-startup-applications \
gnome-system-monitor \
gnome-themes-extra \
gnome-themes-extra-data \
gpg \
gpg-agent \
dirmngr \
gstreamer1.0-alsa \
gstreamer1.0-gl \
gstreamer1.0-pulseaudio \
gstreamer1.0-tools \
gstreamer1.0-plugins-good \
hdparm \
humanity-icon-theme \
"^ibus.*" \
im-config \
iio-sensor-proxy \
info \
initramfs-tools \
install-info \
iptables \
iputils-tracepath \
irqbalance \
kerneloops \
language-selector-common \
language-selector-gnome \
libllvm9 \
libgnome-menu-3-0 \
libproxy1-plugin-networkmanager \
linux-sound-base \
locales \
logrotate \
lshw \
ltrace \
memtest86+ \
micro \
mobile-broadband-provider-info \
modemmanager \
mousetweaks \
mtr-tiny \
nautilus-sendto \
netbase \
netplan.io \
networkd-dispatcher \
network-manager-config-connectivity-ubuntu \
network-manager-gnome \
network-manager \
ntfs-3g \
openprinting-ppds \
openvpn \
os-prober \
"^printer-driver.*" \
packagekit \
pcmciautils \
pkg-config \
plymouth \
poppler-data \
poppler-utils \
popularity-contest \
powermgmt-base \
ppp \
psmisc \
publicsuffix \
pulseaudio \
python3-cairo \
rfkill \
rsync \
rsyslog \
rygel \
snapd \
speech-dispatcher \
squashfs-tools \
strace \
switcheroo-control \
system-config-printer-udev \
tcpdump \
time \
ubuntu-advantage-tools \
ubuntu-docs \
ubuntu-report \
ubuntu-settings \
ufw \
unattended-upgrades \
update-inetd \
update-manager \
update-manager-core \
update-notifier \
upx-ucl \
usb-modeswitch \
usbmuxd \
usbutils \
uuid-runtime \
vim-tiny \
wamerican \
wbritish \
whiptail \
wireless-tools \
whoopsie \
wpasupplicant \
xcursor-themes \
xdg-user-dirs \
xdg-utils \
xfonts-encodings \
xorg-docs-core \
xserver-xephyr \
xserver-xorg-input-wacom \
xserver-xorg-legacy \
xserver-xorg-video-all \
xul-ext-ubufox \
yaru-theme-icon \
yaru-theme-sound \
yelp

# Allow removal of running kernel
sudo rm -f /usr/bin/linux-check-removal
sudo ln -s /usr/bin/true /usr/bin/linux-check-removal

# Remove kernel packages
sudo apt -y --purge remove linux-image-generic-hwe-20.04 "^linux-.*5\..*"

# Absolutely remove all kernels
sudo rm -f /boot/*5*

# Add just make and gcc
# Add base kernel after removing HWE kernel
sudo apt -y install linux-image-5.4.0-66-generic linux-modules-extra-5.4.0-66-generic make gcc libc6-dev

# Add basic networking
sudo apt -y install ifupdown
# Show boot messages instead of splash screen
echo 'GRUB_CMDLINE_LINUX_DEFAULT=""' | sudo tee -a /etc/default/grub
# Use old standard names for interfaces (e.g eth0)
echo 'GRUB_CMDLINE_LINUX=" net.ifnames=0 biosdevname=0"' | sudo tee -a /etc/default/grub
sudo update-grub
echo allow-hotplug eth0 | sudo tee /etc/network/interfaces
echo iface eth0 inet dhcp | sudo tee -a /etc/network/interfaces

# Build a slim initramfs
sudo sed -i 's/^MODULES=most/MODULES=dep/' /etc/initramfs-tools/initramfs.conf
sudo mkinitramfs -c xz -o /boot/initrd.img-*

# Remove extra Linux packages
sudo apt purge -y busybox-initramfs linux-firmware linux-headers-generic "^linux-modules-extra.*" "^linux-header.*" linux-libc-dev

# Upgrade the system
sudo apt -y upgrade

./trim-system
